version: '3.7'

services:
  db:
    platform: linux/x86_64
    build:
      context: ./mysql
    networks:
      - default
    restart: always
    ports:
      - "3309:3306"
    healthcheck:
      test: ["CMD-SHELL", 'mysqladmin ping']
      interval: 1s
      timeout: 10s
      retries: 10
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "rootpass"
      MYSQL_DATABASE: "database"
      MYSQL_USER: "myuser"
      MYSQL_PASSWORD: "mypass"
    volumes:
      - mysql_payments_database_cache:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  cache: 
    image: memcached
    ports: 
      - "11212:11211"
  app:
    build:
      context: ./app
    ports:
      - "3335:3335"
    environment:
      - DBCONN=myuser:mypass@tcp(db:3309)/database
      - ENV=invoiceion
    depends_on:
      db: 
        condition: service_healthy

networks:
  default:
volumes:
  mysql_payments_database_cache: